name: Deploy zenn portal

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/zenn/zenn_portal
            git pull origin main
            npm install
            npm run build
            cp -r .next/static .next/standalone/.next/
            cp -r public .next/standalone/
            cd .next/standalone
            pm2 restart zenn-portal
            pm2 save
